quarkus.http.cors.enabled=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,PUT,POST,DELETE

# Disable browser caching for all responses
#quarkus.http.header."Cache-Control".value=no-cache, no-store, must-revalidate
#quarkus.http.header."Pragma".value=no-cache
#quarkus.http.header."Expires".value=0

#dev config
#quarkus.devservices.enabled=true
quarkus.http.port=8080