# Order Service Configuration
quarkus.http.port=8083
quarkus.http.host=0.0.0.0
quarkus.log.level=INFO
quarkus.log.category."com.dev".level=DEBUG

# CORS
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,PUT,POST,DELETE

# PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5434/order_db
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres

# Hibernate
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=false

# Kafka
kafka.bootstrap.servers=localhost:9092
mp.messaging.outgoing.stock-reserve.connector=smallrye-kafka
mp.messaging.outgoing.stock-reserve.topic=stock.reserve
mp.messaging.outgoing.stock-reserve.value.serializer=org.apache.kafka.common.serialization.StringSerializer

mp.messaging.incoming.stock-reserved.connector=smallrye-kafka
mp.messaging.incoming.stock-reserved.topic=stock.reserved
mp.messaging.incoming.stock-reserved.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.stock-reserved.group.id=order-service

mp.messaging.incoming.stock-insufficient.connector=smallrye-kafka
mp.messaging.incoming.stock-insufficient.topic=stock.insufficient
mp.messaging.incoming.stock-insufficient.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.stock-insufficient.group.id=order-service

mp.messaging.outgoing.cart-clear.connector=smallrye-kafka
mp.messaging.outgoing.cart-clear.topic=cart.clear
mp.messaging.outgoing.cart-clear.value.serializer=org.apache.kafka.common.serialization.StringSerializer

mp.messaging.outgoing.stock-confirm.connector=smallrye-kafka
mp.messaging.outgoing.stock-confirm.topic=stock.confirm
mp.messaging.outgoing.stock-confirm.value.serializer=org.apache.kafka.common.serialization.StringSerializer

# REST Client - Cart Service
quarkus.rest-client.cart-service.url=http://localhost:8082
