# Cart Service Configuration
quarkus.http.port=8082
quarkus.http.host=0.0.0.0
quarkus.log.level=INFO
quarkus.log.category."com.dev".level=DEBUG
# CORS
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,PUT,POST,DELETE

# Redis
quarkus.redis.hosts=redis://localhost:6379

# Bike Service
quarkus.rest-client.bike-service.url=http://localhost:8081

# Kafka
kafka.bootstrap.servers=localhost:9092
mp.messaging.incoming.cart-clear.connector=smallrye-kafka
mp.messaging.incoming.cart-clear.topic=cart.clear
mp.messaging.incoming.cart-clear.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.cart-clear.group.id=cart-service
